/****************************************************************************
this file includes commonly used head files
*****************************************************************************
* @author     developed by Yu Chen
* @copyright  MIT license (see LICENSE file)
*****************************************************************************/

#include <stdint.h>
#include <memory>
#include <fstream>
#include <sstream>
#include <iostream>
#include <fstream>
#include <string>
#include <cmath>
#include <vector>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <thread>
#include <atomic>
#include <tuple> 
#include <iomanip>
#include <functional>
#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdlib>
#include <iterator>
#include <limits>
#include <bitset>
#include <omp.h>
#include <assert.h>
#include <immintrin.h>

