/****************************************************************************
this file includes commonly used head files
*****************************************************************************
* @author     developed by Yu Chen
* @copyright  MIT license (see LICENSE file)
*****************************************************************************/

#include <stdint.h>
#include <memory>
#include <fstream>
#include <sstream>
#include <iostream>
#include <string>
#include <cmath>
#include <vector>
#include <set>
#include <unordered_map>
#include <thread>
#include <iomanip>
#include <functional>
#include <bitset>
#include <omp.h>

#include <boost/algorithm/hex.hpp>
